[package]
name = "oxijade-app"
version = "0.1.0"
edition = "2021"

[dependencies]
oxijade-config = { path = "../oxijade-config" }
oxijade-core = { path = "../oxijade-core" }
eframe = "0.29"
egui = "0.29"
tokio = { version = "1", features = ["full"] }
unicode-width = "0.1"
rfd = "0.14"
dirs-next = "2"
